### ISSUE TITLE
How are you running this?

### ISSUE THREAD

**Issue by scallister** [Ravenbtw/twitch-clip-downloader#1]
I've tried to run this using my browser and using node.
`node content.js` and `node background.js` don't work... should they? How are you running this on your system? Thanks! :)

**Comment by Ravenbtw** [comment]
Hello, sorry if it wasn't clear enough!

This is the source to a Chrome extension, which can be found here:

https://chrome.google.com/webstore/detail/twitch-clip-downloader/klkjnhemebjdikndlpknonjedeefkedk?hl=en

Hopefully that helps. :)
