### ISSUE TITLE
download button no longer shows up

### ISSUE THREAD

**Issue by FloxD** [Ravenbtw/twitch-clip-downloader#4]
heyo raven
since a couple days the download button no longer shows up for whatever reason
using firefox 88.0.1
havent tested in chrome

**Comment by basedbidoof** [comment]
I'm on Firefox 89.0 (64-bit) and I also have no download button. 
I took the min to install it on my Chrome, Version 91.0.4472.77 (Official Build) (64-bit), and it works there.

**Comment by FloxD** [comment]
fixed
